language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

os:
- linux

# install dependencies on Linux (ALSA and JACK)
addons:
  apt:
    packages:
    - libasound2-dev
    - libjack-jackd2-dev
