[package]
name = "mpk-mini-ctl"
version = "0.1.0"
authors = ["Eldad Zack <eldad@fogrefinery.com>"]
description = "AKAI MPK Mini mkII Control Tool"
edition = "2021"

[dependencies]
midir = "0.8.0"
clap = "3.2.8"
regex = "1.5.6"
serde = "1.0.138"
serde_derive = "1.0.137"
serde_yaml = "0.8.24"
log = "0.4.17"
simplelog = "0.12.0"
