[package]
name = "mpk-mini-ctl"
version = "0.1.0"
authors = ["Eldad Zack <eldad@fogrefinery.com>"]
description = "AKAI MPK Mini mkII Control Tool"
edition = "2021"

[dependencies]
midir = "0.8.0"
clap = "3.2.16"
regex = "1.6.0"
serde = "1.0.142"
serde_derive = "1.0.141"
serde_yaml = "0.9.4"
log = "0.4.17"
simplelog = "0.12.0"
