[package]
name = "mpk-mini-edit"
version = "0.1.0"
authors = ["Eldad Zack <eldad@fogrefinery.com>"]
description = "AKAI MPK Mini mkII Settings Editor"

[dependencies]
midir = "0.5.0"
clap = "2.29.4"
regex = "0.2"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_yaml = "0.7.3"
log = "0.4.1"
simplelog = "0.5.0"
