[package]
name = "mpk-mini-ctl"
version = "0.1.0"
authors = ["Eldad Zack <eldad@fogrefinery.com>"]
description = "AKAI MPK Mini mkII Control Tool"
edition = "2021"

[dependencies]
midir = "0.9.0"
clap = { version = "4.0.32", features = ["derive", "cargo"] }
regex = "1.7.1"
serde = "1.0.141"
serde_derive = "1.0.141"
serde_yaml = "0.9.16"
log = "0.4.17"
simplelog = "0.12.0"
anyhow = "1.0.68"
thiserror = "1.0.38"
